project:
  type: book
  output-dir: docs

book:
  title: "SDC1 Macrophage"
  author: 
    - name: "Danyang Zhao, Tao Zeng, Jinyan Huang"
      email: "huangjinyan@zju.edu.cn"
  date: "2025-12-03"
  chapters:
    - index.qmd
    - href: fig2.qmd
      text: Figure2
    - href: fig3.qmd
      text: Figure3
    - href: fig4.qmd
      text: Figure4
    - href: fig5.qmd
      text: Figure5
    - href: fig6.qmd
      text: Figure6
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
execute:
  echo: true
  warning: false
  message: false
  fig.align: 'center'
  
editor: visual

