project:
  type: book
  output-dir: docs

book:
  title: "SDC1 Macrophage"
  author: 
    - name: "Danyang Zhao, Tao Zeng, Jinyan Huang"
      email: "huangjinyan@zju.edu.cn"
  date: "2025-12-03"
  chapters:
    - index.qmd
    - fig2.qmd
    - fig3.qmd
    - fig4.qmd
    - fig5.qmd
    - fig6.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
execute:
  echo: true
  warning: false
  message: false
  fig.align: 'center'
  
editor: visual

