project:
  type: book

book:
  title: "SDC1 Macrophage"
  author: "Danyang Zhao, Jinping Li, Yingjiqiong Liang, Tao Zeng"
  date: "2024-12-03"
  chapters:
    - index.qmd
    - Figure1.qmd
    - Figure2.qmd
    - Figure3.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    
execute:
  echo: true
  warning: false
  message: false
  fig.align: 'center'
  
editor: visual

